### ISSUE TITLE
[Bug] getStoryContext (globalThis) returns undefined

### ISSUE THREAD

**Issue by VickyKoblinski** [storybookjs/test-runner#138]
### Describe the bug

`storyContext` is undefined

```js
// test-runner.js
const { getStoryContext } = require("@storybook/test-runner");

module.exports = {
  async postRender(page, context) {
    const storyContext = await getStoryContext(page, context);
    console.log(storyContext) // undefined
    const globalThis = await page.evaluate(() => globalThis);
    console.log(globalThis) // undefined
  },
};
```

### Steps to reproduce the behavior

Use the above file

### Expected behavior

To be able to access the storyContext like here https://github.com/storybookjs/test-runner/blob/next/.storybook/test-runner.ts

### Screenshots and/or logs

n/a

### Environment

 - OS: mac
 - Node.js version: Tried both 14 and 16

### Additional context

~I think the problem may be because default [`test-runner-jest.config.js`](https://github.com/storybookjs/test-runner/blob/next/playwright/test-runner-jest.config.js) is missing the [globalSetup](https://github.com/storybookjs/test-runner/blob/next/playwright/global-setup.js) and [globalTeardown](https://github.com/storybookjs/test-runner/blob/next/playwright/global-teardown.js) operations that [this repo is using](https://github.com/storybookjs/test-runner/blob/next/test-runner-jest.config.js).~ I was wrong about this, test-runner-jest.config.js does get the setup and teardown from getJestConfig.

Could this be because `globalThis` has been introduced in Jest 28 but we're still on Jest 27?

**Comment by VickyKoblinski** [comment]
It turned out that `globalThis.__STORYBOOK_PREVIEW__.storyStore.loadStory({ storyId })` contained circular dependencies and Playwright doesn't allow you to return Js objects with circular dependencies, which is why I was getting undefined. I'm not sure where they came from, but I think this would be common. Here's my not-so-elegant solution:

```js
    const storyContext = await page.evaluate(
      async ({ storyId }) => {
        const getCircularReplacer = () => {
          const seen = new WeakSet();
          return (key, value) => {
            if (typeof value === "object" && value !== null) {
              if (seen.has(value)) {
                return;
              }
              seen.add(value);
            }
            return value;
          };
        };

        return JSON.parse(
          JSON.stringify(
            await globalThis.__STORYBOOK_PREVIEW__.storyStore.loadStory({ storyId }),
            getCircularReplacer()
          )
        );
      },
      {
        storyId: context.id,
      }
    );
```

**Comment by yannbf** [comment]
Oh wow! That's new to me. Thanks a lot for sharing this @VickyKoblinski ! 🙌  I'll have to chew on this for a bit.
cc @shilman

**Comment by myufa** [comment]
Seeing the same issue, am not able to get this patch to work, @ndelangen any guidance here?

**Comment by myufa** [comment]
have been getting 
page.evaluate: TypeError: Cannot read properties of undefined (reading 'storyStore')
at getStoryContext (node_modules/@storybook/test-runner/dist/cjs/playwright/hooks.js:17:15)

**Comment by yannbf** [comment]
@myufa can you share a reproduction for us to take a look? thanks!

**Comment by MRamonLeon** [comment]
Any update on this?, we're facing this too. Thank you.

**Comment by donaldpipowitch** [comment]
I recently got this error when I tried to run test-runner:

>  page.evaluate: TypeError: Cannot read properties of undefined (reading 'storyStore')

This issue is probably not related to it, but is my first entry in Google and basically the only relevant result. Therefor I want to share here my problem as well in case someone stumbles over it.
I debugged it and the problem is vite. It works with `6.0.8` and started to fail with `6.0.9`. I don't know why yet. If someone has a clue any help would be appreciated. Thanks.

**Comment by Hai-San** [comment]
> have been getting page.evaluate: TypeError: Cannot read properties of undefined (reading 'storyStore') at getStoryContext (node_modules/@storybook/test-runner/dist/cjs/playwright/hooks.js:17:15)

same problem here.

**Comment by custardcream98** [comment]
> have been getting page.evaluate: TypeError: Cannot read properties of undefined (reading 'storyStore') at getStoryContext (node_modules/@storybook/test-runner/dist/cjs/playwright/hooks.js:17:15)

same problem!

I looked into it, and it turns out that `__STORYBOOK_PREVIEW__`, which should be stored in `globalThis`, is undefined.

I suspected that the test might be running before the story is loaded (even though I used `waitForPageReady`). So I tried adding:
```js
await page.waitForFunction(
  () => {
    return (
      !!window.__STORYBOOK_PREVIEW__ &&
      !!window.__STORYBOOK_PREVIEW__.storyStore
    );
  },
  { timeout: 10000 }
);
```

But it still doesn’t work.
