### ISSUE TITLE
collect coverage with ts-jest gives exceeding retry limit

### ISSUE THREAD

**Issue by matart15** [storybookjs/test-runner#141]
### Describe the bug

this happens when i try to collect coverage from tsx files.

```
ui:test: PASS browser: chromium views/RegisterView/RegisterView.stories.tsx (7.776 s)
ui:test: PASS browser: chromium views/TemporaryRegisterView/TemporaryRegisterView/TemporaryRegisterView.stories.tsx (7.756 s)
ui:test: PASS browser: chromium views/RegisterMainView/RegisterMainView.stories.tsx
ui:test: Failed to collect coverage from /Users/***/workplace/***/packages/ui/atoms/Topbar/index.tsx
ui:test: ERROR: Jest worker encountered 3 child process exceptions, exceeding retry limit
ui:test: STACK: Error: Jest worker encountered 3 child process exceptions, exceeding retry limit
ui:test:     at ChildProcessWorker.initialize (/Users/***/workplace/***/packages/ui/node_modules/jest-worker/build/workers/ChildProcessWorker.js:185:21)
ui:test:     at ChildProcessWorker._onExit (/Users/***/workplace/***/packages/ui/node_modules/jest-worker/build/workers/ChildProcessWorker.js:269:12)
ui:test:     at ChildProcess.emit (node:events:520:28)
ui:test:     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

this is my config

| working  | error happens  |
|---|---|
| ![code1](https://user-images.githubusercontent.com/17027219/178400893-6062dbd8-2203-43a1-bcd4-0baa12ce15c2.png)  |  ![code2](https://user-images.githubusercontent.com/17027219/178400919-013accd9-0305-4cbe-aa66-ce903d943930.png) |

error happens if I input `collectCoverage: true,` to `test-runner-jest.config.js` file

### Environment

 - OS: OSX
 - Node.js version:16.14.0
 - NPM version: 8.3.1

**Comment by matart15** [comment]
Sorry. False alert. 

this solved the problem

```js
  transform: {
    '^.+\\.stories\\.[jt]sx?$': '@storybook/test-runner/playwright/transform',
    '^.+\\.[jt]sx?$': 'ts-jest',
    "\\.(jpg|ico|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "./mocks/fileMock.js",
    "\\.(css|less)$": "./mocks/fileMock.js"
    // '^.+\\.[jt]sx?$': 'babel-jest'
  },
```
