### ISSUE TITLE
[Bug] Cannot use with ESM storybook config file

### ISSUE THREAD

**Issue by IanVS** [storybookjs/test-runner#200]
### Describe the bug

I upgraded storybook to 7.0, which allows the use of ESM config files (both js and ts).  So, my `.storybook/main.ts` file includes this at the top now:

```js
import path from 'node:path';
```

But, when I run the test-runner, I get an error:

```
/Users/ianvs/code/defined/webclient/.storybook/main.ts:2
import path from 'node:path';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Module._compile (/Users/ianvs/code/defined/webclient/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.newLoader [as .ts] (/Users/ianvs/code/defined/webclient/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

### Steps to reproduce the behavior

1. Upgrade to storybook 7
2. Use an ESM storybook config file with an `import` statement
3. Try to run test-runner

### Expected behavior

The test-runner should load esm config files

### Screenshots and/or logs

See above

### Environment

```
Environment Info:

  System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.16.0 - ~/.volta/tools/image/node/16.16.0/bin/node
    Yarn: 1.22.19 - ~/.volta/bin/yarn
    npm: 8.15.0 - ~/.volta/tools/image/npm/8.15.0/bin/npm
  Browsers:
    Firefox: 105.0.2
    Safari: 15.6.1
  npmPackages:
    @storybook/addon-a11y: ^7.0.0-alpha.35 => 7.0.0-alpha.35
    @storybook/addon-actions: ^7.0.0-alpha.35 => 7.0.0-alpha.35
    @storybook/addon-docs: ^7.0.0-alpha.35 => 7.0.0-alpha.35
    @storybook/addon-essentials: ^7.0.0-alpha.35 => 7.0.0-alpha.35
    @storybook/addon-interactions: ^7.0.0-alpha.35 => 7.0.0-alpha.35
    @storybook/addon-links: ^7.0.0-alpha.35 => 7.0.0-alpha.35
    @storybook/addon-postcss: ^3.0.0-alpha.1 => 3.0.0-alpha.1
    @storybook/addons: ^7.0.0-alpha.35 => 7.0.0-alpha.35
    @storybook/expect: ^27.5.2-0 => 27.5.2-0
    @storybook/jest: ^0.0.10 => 0.0.10
    @storybook/react: ^7.0.0-alpha.35 => 7.0.0-alpha.35
    @storybook/react-vite: ^7.0.0-alpha.35 => 7.0.0-alpha.35
    @storybook/test-runner: ^0.7.2 => 0.7.2
    @storybook/testing-library: ^0.0.14-next.0 => 0.0.14-next.0
    @storybook/testing-react: ^1.3.0 => 1.3.0
```

### Additional context

I had a hard time noticing and finding out where this error was coming from, and will push up a PR to clean up error handling just a bit.

**Comment by kaelig** [comment]
From what I can tell from my logs, the error came from:

`/node_modules/@storybook/test-runner/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js`

I noticed this package was pulling an old version of `@storybook/core-common`, so I forced this resolution:
```json5
// package.json
  "resolutions": {
    "@storybook/core-common": "7.0.0-alpha.37"
  },
```

I uninstalled/reinstalled `@storybook/test-runner`, and the error went away.

**Comment by IanVS** [comment]
Great catch @kaelig!  I've opened https://github.com/storybookjs/test-runner/pull/207 which I think should take care of this.

**Comment by IanVS** [comment]
This is fixed with https://github.com/storybookjs/test-runner/releases/tag/v0.10.0-next.0
