### ISSUE TITLE
[Bug]  ReferenceError: window is not defined

### ISSUE THREAD

**Issue by gabrielperales** [storybookjs/test-runner#249]
### Describe the bug

I'm trying to run my tests in the CLI but I'm getting the error `ReferenceError: window is not defined`.

This is my `test-runner-jest.config.js`:

```javascript
const { getJestConfig } = require('@storybook/test-runner');

module.exports = {
  // The default configuration comes from @storybook/test-runner
  ...getJestConfig(),
  transform: {
    '^.+\\.[t]sx?$': 'babel-jest',
    '^.+\\.scss$': 'jest-scss-transform',
  },
  modulePaths: ['src', 'node-modules'],
  moduleNameMapper: {
    '^test/(.*)$': '<rootDir>/test/$1',
    '^@config': '<rootDir>/src/config',
  }
};
```

### Screenshots and/or logs

![CleanShot 2023-01-24 at 11 05 11](https://user-images.githubusercontent.com/1859128/214263759-60abcd4c-391e-468e-8196-de825a5ad1bd.png)

### Environment

 - OS: Mac OS 12.4
 - Node.js version: 18.13.0
 - Yarn version: 1.22.19

### Additional context

I'm using TypeScript and I have the tests running already on Storybook. The module name mapper seems to be working right, but for some reason seems like the tests are not running in the right test environment.

**Comment by gabrielperales** [comment]
Seems like it is trying to run my unit tests in my stories because it is returning this error:


```
 FAIL  src/UI/Drawer/Drawer.story.tsx
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:172:18)
      at node_modules/@jest/core/build/TestScheduler.js:300:17
      at node_modules/emittery/index.js:311:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/emittery/index.js:309:23)
```

**Comment by gabrielperales** [comment]
I think that the problem was related to the transformation of the stories into tests. My stories files are in files with this format `*.story.tsx`, and the default transform matches with files `*.stories.[jt]sx`, so the transform wasn't being applied.

I managed to make it work (some test are passing, but others aren't), so I think I still have some issues.
