### ISSUE TITLE
page.addScriptTag: Refused to execute inline script

### ISSUE THREAD

**Issue by nicolasburtey** [storybookjs/test-runner#275]
when trying to run the test running on a react native project, I run into this issue:

```
 % yarn test-storybook --url http://localhost:7007 --maxWorkers=2
watchman warning:  Recrawled this watch 1 times, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '/Users/n/Code/react-native-template-new-architecture' ; watchman watch-project '/Users/n/Code/react-native-template-new-architecture'`

 FAIL   browser: chromium  src/components/text/text.stories.tsx
  ● Test suite failed to run

    page.addScriptTag: Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-gO06W1rzmjlE4IbFnX8Hjiu42nH+w7cA61VdAG7f8eM='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

      at setupPage (node_modules/@storybook/test-runner/dist/cjs/setup-page.js:63:14)
      at CustomEnvironment.setup (node_modules/@storybook/test-runner/playwright/custom-environment.js:9:5)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.428 s
Ran all test suites.
```

an easy way to reproduce this issue is to add the test runner from this repo:

https://github.com/leotm/react-native-template-new-architecture

**Comment by kla-trackunit** [comment]
Any workarounds for this issue? :)

**Comment by yannbf** [comment]
Hey there! Sorry, the test-runner doesn't support React Native directly (like provided in the example template), however it does work if you use the react-native-web addon. I added a remark about that in the docs here:
https://github.com/storybookjs/test-runner#react-native-support
