### ISSUE TITLE
[Bug]  Jest: Got error running globalSetup 

### ISSUE THREAD

**Issue by kkumarlinz** [storybookjs/test-runner#308]
### Describe the bug

npm run test-storybook
 test-storybook

TypeError: Jest: Got error running globalSetup - C:\Users\kkumar\code\web\node_modules\@storybook\test-runner\playwright\global-setup.js, reason: Class extends value undefined is not a constructor or null
    at getPlaywrightEnv (C:\Users\kkumar\code\web\node_modules\jest-playwright-preset\lib\PlaywrightEnvironment.js:59:5)
    at Object.<anonymous> (C:\Users\kkumar\code\web\node_modules\jest-playwright-preset\lib\PlaywrightEnvironment.js:245:48)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.newLoader (C:\Users\kkumar\code\web\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\kkumar\code\web\node_modules\jest-playwright-preset\index.js:1:18)

### Expected behavior

Should run test 

### Screenshots and/or logs

If applicable, add screenshots and/or logs to help explain your problem.

### Environment

 - Node.js version: [e.g. v12.17.0]
 - NPM version: [e.g. 6.14.4]
 - Browser (if applicable): [e.g. chrome, safari]
 - Browser version (if applicable): [e.g. 22]
 - Device (if applicable): [e.g. iPhone6]

**Comment by nikkialgar** [comment]
I had the same error. Moving `vite` to be a `dependency` rather than a `devDependency` fixed it for me.
