### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by david-morris** [storybookjs/test-runner#329]
**Describe the bug**
Invoking with a path regex causes an error

**To Reproduce**
1. invoke test-storybook with a positional regex pattern for story path
3. See error

**Expected behavior**
The test runner should run the stories matching the pattern.

**Screenshots**
```
$ test-storybook --config-dir libs/storybook/.storybook --maxWorkers=2 '.*MissingApp.*'
TypeError: rawArgv2.replace is not a function
    at <anonymous> (/workspaces/react/node_modules/@storybook/test-runner/node_modules/jest-cli/build/cli/index.js:188:40)
    at Array.map (<anonymous>)
    at buildArgv (/workspaces/react/node_modules/@storybook/test-runner/node_modules/jest-cli/build/cli/index.js:188:17)
    at Object.run (/workspaces/react/node_modules/@storybook/test-runner/node_modules/jest-cli/build/cli/index.js:147:18)
    at async executeJestPlaywright (/workspaces/react/node_modules/@storybook/test-runner/dist/test-storybook.js:128:3)
    at async main (/workspaces/react/node_modules/@storybook/test-runner/dist/test-storybook.js:272:3)
```

**System**
Please paste the results of `npx storybook@latest info` here.

Environment Info:

  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
  Binaries:
    Node: 18.16.1 - /usr/local/share/nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/share/nvm/versions/node/v18.16.1/bin/npm
  npmPackages:
    @storybook/addon-essentials: 7.0.23 => 7.0.23 
    @storybook/addon-interactions: 7.0.23 => 7.0.23 
    @storybook/core-common: ^7.0.23 => 7.0.23 
    @storybook/core-server: 7.0.23 => 7.0.23 
    @storybook/jest: ^0.1.0 => 0.1.0 
    @storybook/nextjs: 7.0.23 => 7.0.23 
    @storybook/test-runner: ^0.11.0 => 0.11.0 
    @storybook/testing-library: ^0.2.0 => 0.2.0 

**Additional context**
The other arguments for specifying specific files don't work.

**Comment by yannbf** [comment]
Hey there @david-morris! This was an unfortunate issue that got introduced at a previous version. People update the test-runner to 0.13.0, it should be working now. Thank you!
