### ISSUE TITLE
[bug] Error: `Your test suite must contain at least one test.`

### ISSUE THREAD

**Issue by gevgeny** [storybookjs/test-runner#359]
Test runner cannot generate test case from my story. The story rendered with no problems in Storybook, but when I run `test-storybook`, I get: 

```
 FAIL   browser: chromium  .../MyComponent/stories.jsx
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@storybook/test-runner/node_modules/@jest/core/build/TestScheduler.js:172:18)
      at node_modules/@storybook/test-runner/node_modules/@jest/core/build/TestScheduler.js:300:17
      at node_modules/emittery/index.js:311:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/emittery/index.js:309:23)
```
**Sources**

`.../MyComponent/stories.jsx`:  

```js
import { expect } from '@storybook/jest';

const MyComponent = () => 'hello world';

export default {
  title: 'MyComponent',
  component: MyComponent,
};

export const MyStory = {
  play: async () => {
    expect(42).toBe(42);
  },
};
```
`test-runner-jest.config.js`:

```js
const { getJestConfig } = require('@storybook/test-runner');


const config = getJestConfig();
config.testMatch = ['<rootDir>/**/MyComponent/stories.jsx']

module.exports = config;
```

**System**
```
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 16.6
  npmPackages:
    @storybook/addon-actions: ^7.4.0 => 7.4.1 
    @storybook/addon-essentials: ^7.4.0 => 7.4.1 
    @storybook/addon-interactions: ^7.4.0 => 7.4.1 
    @storybook/addon-knobs: ^7.0.2 => 7.0.2 
    @storybook/addon-links: ^7.4.0 => 7.4.1 
    @storybook/addon-viewport: ^7.4.0 => 7.4.1 
    @storybook/jest: 0.2.1 => 0.2.1 
    @storybook/nextjs: ^7.4.0 => 7.4.1 
    @storybook/react: ^7.4.0 => 7.4.1 
    @storybook/test-runner: 0.13.0 => 0.13.0 
    @storybook/testing-library: 0.2.0 => 0.2.0 
```

**Comment by gevgeny** [comment]
Here is what I have found in jest cache:

```js
db5cd9409e7f083b8ae7f94af011077a
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = exports.MyStory = void 0;
var _jest = require("@storybook/jest");
const MyComponent = () => 'hello world';
var _default = exports.default = {
  title: 'MyComponent',
  component: MyComponent
};
const MyStory = exports.MyStory = {
  play: async () => {
    (0, _jest.expect)(42).toBe(42);
  }
};
//# sourceMappingURL=data:application/json; ...
```

there is no any jest spefiic calls in here, so looks like indeed, the code is transformed but not for test running.

**Comment by gevgeny** [comment]
Turns out it was naming problem. The playwright transformer from the default config is applied only when your stories has `*.stories.jsx` not `stories.js` name
```
 '^.+\\.stories\\.[jt]sx?$': '.../node_modules/@storybook/test-runner/playwright/transform.js'
```
