### ISSUE TITLE
[bug] test-runner doesn't execute in the project folder

### ISSUE THREAD

**Issue by ghost** [storybookjs/test-runner#415]
**Describe the bug**
Hello, I'm trying to use storybook and I just followed the docs to setup the test-runner addon. They are so simple and I've tried to execute them on other devices and everything went fine. It seems that for some reason I still don't get it, on my macbook it's not executing the script in the project folder, but instead it search on every folder in my laptop.

Here's the output
```bash
manuel@macbookpro test2-storybook % npm run test-storybook

> test2-storybook@0.0.0 test-storybook
> test-storybook

jest-haste-map: Haste module naming collision: vscode-typescript-vue-plugin
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/.vscode/extensions/vue.vscode-typescript-vue-plugin-1.8.25/package.json
    * <rootDir>/.vscode/extensions/vue.vscode-typescript-vue-plugin-1.8.24/package.json

jest-haste-map: Haste module naming collision: volar
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/.vscode/extensions/vue.volar-1.8.24/package.json
    * <rootDir>/.vscode/extensions/vue.volar-1.8.25/package.json

jest-haste-map: Haste module naming collision: vscode-css-peek
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/.vscode/extensions/pranaygp.vscode-css-peek-4.4.1/package.json
    * <rootDir>/.vscode/extensions/pranaygp.vscode-css-peek-4.4.1/server/package.json

jest-haste-map: Haste module naming collision: python
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/.vscode/extensions/ms-python.python-2023.20.0/package.json
    * <rootDir>/.vscode/extensions/ms-python.python-2023.20.0/out/client/package.json

jest-haste-map: Haste module naming collision: color-highlight
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/.vscode/extensions/naumovs.color-highlight-2.5.0/package.json
    * <rootDir>/.vscode/extensions/naumovs.color-highlight-2.5.0/color-highlight-2.5.0/extension/package.json

jest-haste-map: Haste module naming collision: expo-push-service
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Dev/repos/applied/expo-push-service/package.json
    * <rootDir>/Dev/repos/applied/expo-push-service/build/package.json

jest-haste-map: Haste module naming collision: tooltipster
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Dev/repos/applied/WebSentinel/dist/tooltipster/package.json
    * <rootDir>/Dev/repos/applied/WebSentinel/public/tooltipster/package.json

jest-haste-map: Haste module naming collision: go
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/.vscode/extensions/golang.go-0.40.0/package.json
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/go/package.json

jest-haste-map: Haste module naming collision: bat
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/bat/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/bat/package.json

jest-haste-map: Haste module naming collision: clojure
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/clojure/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/clojure/package.json

jest-haste-map: Haste module naming collision: cpp
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/cpp/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/cpp/package.json

jest-haste-map: Haste module naming collision: coffeescript
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/coffeescript/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/coffeescript/package.json

jest-haste-map: Haste module naming collision: csharp
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/csharp/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/csharp/package.json

jest-haste-map: Haste module naming collision: dart
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/dart/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/dart/package.json

jest-haste-map: Haste module naming collision: css
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/css/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/css/package.json

jest-haste-map: Haste module naming collision: diff
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/diff/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/diff/package.json

jest-haste-map: Haste module naming collision: docker
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/docker/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/docker/package.json

jest-haste-map: Haste module naming collision: fsharp
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/fsharp/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/fsharp/package.json

jest-haste-map: Haste module naming collision: erlang-ls
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/erlang/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/erlang/package.json

jest-haste-map: Haste module naming collision: git-base
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/git-base/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/git-base/package.json

jest-haste-map: Haste module naming collision: groovy
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/groovy/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/groovy/package.json

jest-haste-map: Haste module naming collision: html
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/html/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/html/package.json

jest-haste-map: Haste module naming collision: ini
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/ini/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/ini/package.json

jest-haste-map: Haste module naming collision: hlsl
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/hlsl/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/hlsl/package.json

jest-haste-map: Haste module naming collision: handlebars
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/handlebars/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/handlebars/package.json

jest-haste-map: Haste module naming collision: java
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/java/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/java/package.json

jest-haste-map: Haste module naming collision: json
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/json/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/json/package.json

jest-haste-map: Haste module naming collision: javascript
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/javascript/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/javascript/package.json

jest-haste-map: Haste module naming collision: vscode-jsp
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/jsp/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/jsp/package.json

jest-haste-map: Haste module naming collision: julia
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/julia/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/julia/package.json

jest-haste-map: Haste module naming collision: log
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/log/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/log/package.json

jest-haste-map: Haste module naming collision: latex
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/latex/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/latex/package.json

jest-haste-map: Haste module naming collision: lua
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/lua/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/lua/package.json

jest-haste-map: Haste module naming collision: make
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/make/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/make/package.json

jest-haste-map: Haste module naming collision: less
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/less/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/less/package.json

jest-haste-map: Haste module naming collision: markdown
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/markdown-basics/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/markdown-basics/package.json

jest-haste-map: Haste module naming collision: markdown-math
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/markdown-math/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/markdown-math/package.json

jest-haste-map: Haste module naming collision: mdx
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/mdx/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/mdx/package.json

jest-haste-map: Haste module naming collision: perl
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/perl/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/perl/package.json

jest-haste-map: Haste module naming collision: objective-c
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/objective-c/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/objective-c/package.json

jest-haste-map: Haste module naming collision: powershell
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/powershell/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/powershell/package.json

jest-haste-map: Haste module naming collision: php
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/php/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/php/package.json

jest-haste-map: Haste module naming collision: pug
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/pug/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/pug/package.json

jest-haste-map: Haste module naming collision: r
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/r/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/r/package.json

jest-haste-map: Haste module naming collision: razor
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/razor/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/razor/package.json

jest-haste-map: Haste module naming collision: restructuredtext
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/restructuredtext/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/restructuredtext/package.json

jest-haste-map: Haste module naming collision: ruby
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/ruby/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/ruby/package.json

jest-haste-map: Haste module naming collision: rust
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/rust/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/rust/package.json

jest-haste-map: Haste module naming collision: scss
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/scss/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/scss/package.json

jest-haste-map: Haste module naming collision: shaderlab
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/shaderlab/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/shaderlab/package.json

jest-haste-map: Haste module naming collision: search-result
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/search-result/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/search-result/package.json

jest-haste-map: Haste module naming collision: shellscript
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/shellscript/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/shellscript/package.json

jest-haste-map: Haste module naming collision: swift
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/swift/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/swift/package.json

jest-haste-map: Haste module naming collision: vb
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/vb/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/vb/package.json

jest-haste-map: Haste module naming collision: sql
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/sql/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/sql/package.json

jest-haste-map: Haste module naming collision: language-viml
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/viml/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/viml/package.json

jest-haste-map: Haste module naming collision: xml
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/xml/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/xml/package.json

jest-haste-map: Haste module naming collision: terraform
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/terraform/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/terraform/package.json

jest-haste-map: Haste module naming collision: twig-language-2
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/twig/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/twig/package.json

jest-haste-map: Haste module naming collision: typescript
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/typescript-basics/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/typescript-basics/package.json

jest-haste-map: Haste module naming collision: yaml
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/yaml/package.json
    * <rootDir>/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/yaml/package.json

jest-haste-map: Haste module naming collision: @jupyter-widgets/jupyterlab-manager
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Library/Python/3.9/share/jupyter/labextensions/@jupyter-widgets/jupyterlab-manager/package.json
    * <rootDir>/Library/Python/3.9/lib/python/site-packages/jupyterlab_widgets/labextension/package.json

jest-haste-map: Haste module naming collision: jupyterlab_pygments
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/Library/Python/3.9/share/jupyter/labextensions/jupyterlab_pygments/package.json
    * <rootDir>/Library/Python/3.9/lib/python/site-packages/jupyterlab_pygments/labextension/package.json

 FAIL   browser: chromium  src/stories/Header.stories.ts
  ● Test suite failed to run

    The name `handlebars` was looked up in the Haste module map. It cannot be resolved, because there exists several different files, or packages, that provide a module for that particular name and platform. The platform is generic (no extension). You must delete or exclude files until there remains only one of these:

      * `/Users/manuel/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/handlebars/package.json` (package)
      * `/Users/manuel/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/handlebars/package.json` (package)

      at ModuleMap._assertNoDuplicates (Dev/studio/test2-storybook/node_modules/jest-haste-map/build/ModuleMap.js:189:11)
      at Object.<anonymous> (Dev/studio/test2-storybook/node_modules/@storybook/core-common/dist/index.js:19:6287)
      at Object.<anonymous> (Dev/studio/test2-storybook/node_modules/@storybook/test-runner/dist/config/jest-playwright.js:36:26)
      at Object.<anonymous> (Dev/studio/test2-storybook/node_modules/@storybook/test-runner/dist/index.js:19:25)
      at Object.<anonymous> (Dev/studio/test2-storybook/node_modules/@storybook/test-runner/playwright/jest-setup.js:1:173)

 FAIL   browser: chromium  src/stories/Page.stories.ts
  ● Test suite failed to run

    The name `handlebars` was looked up in the Haste module map. It cannot be resolved, because there exists several different files, or packages, that provide a module for that particular name and platform. The platform is generic (no extension). You must delete or exclude files until there remains only one of these:

      * `/Users/manuel/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/handlebars/package.json` (package)
      * `/Users/manuel/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/handlebars/package.json` (package)

      at ModuleMap._assertNoDuplicates (Dev/studio/test2-storybook/node_modules/jest-haste-map/build/ModuleMap.js:189:11)
      at Object.<anonymous> (Dev/studio/test2-storybook/node_modules/@storybook/core-common/dist/index.js:19:6287)
      at Object.<anonymous> (Dev/studio/test2-storybook/node_modules/@storybook/test-runner/dist/config/jest-playwright.js:36:26)
      at Object.<anonymous> (Dev/studio/test2-storybook/node_modules/@storybook/test-runner/dist/index.js:19:25)
      at Object.<anonymous> (Dev/studio/test2-storybook/node_modules/@storybook/test-runner/playwright/jest-setup.js:1:173)

 FAIL   browser: chromium  src/stories/Button.stories.ts
  ● Test suite failed to run

    The name `handlebars` was looked up in the Haste module map. It cannot be resolved, because there exists several different files, or packages, that provide a module for that particular name and platform. The platform is generic (no extension). You must delete or exclude files until there remains only one of these:

      * `/Users/manuel/Applications/Android Studio.app/Contents/plugins/textmate/lib/bundles/handlebars/package.json` (package)
      * `/Users/manuel/Applications/PyCharm Community Edition.app/Contents/plugins/textmate/lib/bundles/handlebars/package.json` (package)

      at ModuleMap._assertNoDuplicates (Dev/studio/test2-storybook/node_modules/jest-haste-map/build/ModuleMap.js:189:11)
      at Object.<anonymous> (Dev/studio/test2-storybook/node_modules/@storybook/core-common/dist/index.js:19:6287)
      at Object.<anonymous> (Dev/studio/test2-storybook/node_modules/@storybook/test-runner/dist/config/jest-playwright.js:36:26)
      at Object.<anonymous> (Dev/studio/test2-storybook/node_modules/@storybook/test-runner/dist/index.js:19:25)
      at Object.<anonymous> (Dev/studio/test2-storybook/node_modules/@storybook/test-runner/playwright/jest-setup.js:1:173)

Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        2.155 s
Ran all test suites.

```

**To Reproduce**

I just created a new react+typescript project using vite, then installing storybook and the test-runner

**Expected behavior**
It would just work and pass the smoke tests, it works fine on other laptops and in a docker container in mine.

**Screenshots**

**System**
```bash
Storybook Environment Info:

  System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    npm: 10.2.3 - /usr/local/bin/npm <----- active
  Browsers:
    Chrome: 119.0.6045.199
    Safari: 17.1
  npmPackages:
    @storybook/addon-essentials: ^7.6.3 => 7.6.3 
    @storybook/addon-interactions: ^7.6.3 => 7.6.3 
    @storybook/addon-links: ^7.6.3 => 7.6.3 
    @storybook/addon-onboarding: ^1.0.9 => 1.0.9 
    @storybook/blocks: ^7.6.3 => 7.6.3 
    @storybook/jest: ^0.2.3 => 0.2.3 
    @storybook/react: ^7.6.3 => 7.6.3 
    @storybook/react-vite: ^7.6.3 => 7.6.3 
    @storybook/test: ^7.6.3 => 7.6.3 
    @storybook/test-runner: ^0.16.0 => 0.16.0 
    @storybook/testing-library: ^0.2.2 => 0.2.2 
    eslint-plugin-storybook: ^0.6.15 => 0.6.15 
    storybook: ^7.6.3 => 7.6.3 
```

**Additional context**
When I execute the test runner after rebooting my laptop, it asks for permissions to access other apps. The result doesn't change if give or not those permissions.

**Comment by tmanuel94** [comment]
#### Little update

It seems that running it with the `-s` flag makes it work correctly. Still I haven't found what's causing this issue

**Comment by jonniebigodes** [comment]
To everyone who runs into this issue, this is technically not an issue but rather an implementation quirk. I ran into the same situation, and what is happening is how the test-runner is designed to work accounting for monorepo environments; it looks up the top-level `.git` folder. However, if it's unable to find it, it continues the search. Eventually, it finds the one you and I experienced, and then, out of the project directory, it starts generating `package.json` files in those folders incorrectly. You could run `git init` on your project and commit the changes, and the problem should disappear. I tested this, and it checked out. Also, you could use the `-s` flag, or in other terms, the `index.json` mode, as it will overlook the root dir and user stories, it will run another heuristics, and with that, it circumvents the issue. 

I will close the issue for now, but I will be more than glad to re-open it if there are other circumstances where the problem arises and, if need be, adjust the documentation.

Hope everyone has a fantastic holiday season.

Stay safe
