### ISSUE TITLE
[bug] preVisit accesses the story store before the index is ready

### ISSUE THREAD

**Issue by sergei-maertens** [storybookjs/test-runner#442]
**Describe the bug**

We have the test-runner.js implement with the `preVisit` to apply the different viewports when running tests, per the [README](https://github.com/storybookjs/test-runner?tab=readme-ov-file#preconfiguring-viewport-size).

After upgrading to Storybook 8, our tests fail in a flaky way, e.g.:

```
 FAIL  src/components/PostCompletionViews/PostCompletionView.stories.js
  ● Private API / Post completion views  › Generic › smoke-test

    page.evaluate: SB_PREVIEW_API_0011 (StoryStoreAccessedBeforeInitializationError): Cannot access the Story Store until the index is ready.

    It is not recommended to use methods directly on the Story Store anyway, in Storybook 9 we will
    remove access to the store entirely

      at Object.get (http:/127.0.0.1:6006/sb-preview/runtime.js:118:5542)
      at __getContext (<anonymous>:215:54)
      at eval (eval at evaluate (:226:30), <anonymous>:1:29)
      at UtilityScript.evaluate (<anonymous>:228:17)
      at UtilityScript.<anonymous> (<anonymous>:1:44)
      at getStoryContext (node_modules/@storybook/test-runner/dist/index.js:15306:15)
      at getStoryContext (.storybook/test-runner.js:9:27)
      at src/components/PostCompletionViews/PostCompletionView.stories.js:151:64
      at step (src/components/PostCompletionViews/PostCompletionView.stories.js:109:23)
      at Object.next (src/components/PostCompletionViews/PostCompletionView.stories.js:50:20)
      at asyncGeneratorStep (src/components/PostCompletionViews/PostCompletionView.stories.js:4:28)
      at _next (src/components/PostCompletionViews/PostCompletionView.stories.js:22:17)
      at src/components/PostCompletionViews/PostCompletionView.stories.js:27:13
      at src/components/PostCompletionViews/PostCompletionView.stories.js:19:16
      at testFn (src/components/PostCompletionViews/PostCompletionView.stories.js:211:49)
      at Object.<anonymous> (src/components/PostCompletionViews/PostCompletionView.stories.js:224:33)
      at step (src/components/PostCompletionViews/PostCompletionView.stories.js:109:23)
      at Object.next (src/components/PostCompletionViews/PostCompletionView.stories.js:50:20)
      at asyncGeneratorStep (src/components/PostCompletionViews/PostCompletionView.stories.js:4:28)
      at _next (src/components/PostCompletionViews/PostCompletionView.stories.js:22:17)
      at src/components/PostCompletionViews/PostCompletionView.stories.js:27:13
      at Object.<anonymous> (src/components/PostCompletionViews/PostCompletionView.stories.js:19:16)
```

In the browser, there are no problems, only happens when using the test-runner.

**To Reproduce**

Unfortunately I don't see a way to reproduce this reliably, but our repository is public: https://github.com/open-formulieren/open-forms-sdk/tree/chore/662-sb-upgrade

```bash
# clone repo
npm ci
npm run storybook
```
and in a different tab/shell:

```bash
npm run test:storybook
```

**Expected behavior**

Tests only run when the story story is ready

**Screenshots**
n/a

**System**

```
Storybook Environment Info:

  System:
    OS: Linux 6.7 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.21 - /usr/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm <----- active
    pnpm: 8.15.2 - /usr/bin/pnpm
  npmPackages:
    @storybook/addon-actions: ^8.0.0 => 8.0.0 
    @storybook/addon-coverage: ^1.0.1 => 1.0.1 
    @storybook/addon-essentials: ^8.0.0 => 8.0.0 
    @storybook/addon-interactions: ^8.0.0 => 8.0.0 
    @storybook/addon-links: ^8.0.0 => 8.0.0 
    @storybook/addon-webpack5-compiler-babel: ^3.0.3 => 3.0.3 
    @storybook/components: ^8.0.0 => 8.0.0 
    @storybook/manager-api: ^8.0.0 => 8.0.0 
    @storybook/preview-api: ^8.0.0 => 8.0.0 
    @storybook/react: ^8.0.0 => 8.0.0 
    @storybook/react-webpack5: ^8.0.0 => 8.0.0 
    @storybook/test: ^8.0.0 => 8.0.0 
    @storybook/test-runner: ^0.17.0 => 0.17.0 
    @storybook/types: ^8.0.0 => 8.0.0 
    msw-storybook-addon: ^1.10.0 => 1.10.0 
    storybook: ^8.0.0 => 8.0.0 
    storybook-addon-remix-react-router: ^3.0.0 => 3.0.0 
    storybook-addon-themes: ^6.1.0 => 6.1.0 
    storybook-react-intl: ^3.0.1 => 3.0.1 

```

**Additional context**

I have an outdated theme addon that needs to be replaced still, no idea if that could be messing things up :thinking:

**Comment by sergei-maertens** [comment]
Interestingly enough, this doesn't seem to happen with a production build since our CI is passing: https://github.com/open-formulieren/open-forms-sdk/actions/runs/8340149970/job/22823603724?pr=663

**Comment by AlmarAubel** [comment]
We have the same problem. If I  add `await waitForPageReady(page);`  i runs less flakky.

```js
const config: TestRunnerConfig = {
  async preVisit(page, story) {
    await waitForPageReady(page);
    }
}
```

**Comment by ItaiCovver** [comment]
We have the same problem but adding `waitForPageReady` stalls indefinitely on this line

```ts
await page.waitForLoadState("networkidle")
```

Interestingly enough this only happens in our CI flow but not locally. In both we run identical docker containers

**Comment by VizTheWiz** [comment]
I'm having the same issue, it happens when running storybook dev with the --ci flag (Without the CI flag, when the playground webpage is opened, this does not occur).
However, it seems to resolve if I immediately run test-runner after this fail, but it takes longer than usual (10s as opposed to around 4s). Another consecutive call to test-runner takes the expected duration.

This only seems to happen in one specific instance, which also relies on Apollo GraphQL client mocked provider and is overall more complex. Smaller standalone packages with simple components do not seem to have this issue, and the tests run successfully.

For reference, this is the output from storybook info, using Vite:

```
Storybook Environment Info:

  System:
    OS: Linux 6.5 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm <----- active
    pnpm: 8.15.4 - /usr/local/share/npm-global/bin/pnpm
  npmPackages:
    @storybook/addon-essentials: ^8.0.5 => 8.0.5 
    @storybook/addon-interactions: ^8.0.5 => 8.0.5 
    @storybook/addon-links: ^8.0.5 => 8.0.5 
    @storybook/addon-onboarding: ^8.0.5 => 8.0.5 
    @storybook/blocks: ^8.0.5 => 8.0.5 
    @storybook/react: ^8.0.5 => 8.0.5 
    @storybook/react-vite: ^8.0.5 => 8.0.5 
    @storybook/test: ^8.0.5 => 8.0.5 
    @storybook/test-runner: ^0.17.0 => 0.17.0 
    eslint-plugin-storybook: ^0.8.0 => 0.8.0 
    storybook: ^8.0.5 => 8.0.5 
```

**Comment by Mil4n0r** [comment]
Any updates on this? I am having the exact same problem.

**Comment by noranda** [comment]
Same here! Same problem.

**Comment by kdrbek06** [comment]
Same issue here in `postVisit` hook

```ts
async postVisit(page, context) {
    await waitForPageReady(page);
    .
    .
}```

**Comment by dorsharonfuse** [comment]
any update on this?
We're getting the same problem, and the tests run flaky because of it.

**Comment by Jero786** [comment]
Any update on this? I encountered the same issue too.

**Comment by jorgeortega** [comment]
With a very small set of stories, `test-storybook --maxWorkers=1` worked for me locally. Haven't tried yet on CI.

**Comment by noranda** [comment]
Any update on this? 🥺

**Comment by dmaier-indeed** [comment]
Also encountering this. My code is using the recipe to set the viewport size as in [this example](https://storybook.js.org/docs/writing-tests/test-runner#accessing-story-information-with-the-test-runner) from the docs.

Changing to `postVisit` sort of works, but then there are still a few renders with whatever the previous viewport size was, so it's flaky

**Comment by Geloosa** [comment]
Encountering the same with vue components, one time the tests pass, the next time this error occurs, and in different stories every time.

**Comment by VizTheWiz** [comment]
I'm wondering if this issue is even going to get addressed, or rather if for storybook 8 is going to completely phase out test-runner in favor of the newly announced vitest plugin:

[](https://storybook.js.org/blog/storybook-8-3/)
[](https://storybook.js.org/docs/writing-tests/vitest-plugin?ref=storybookblog.ghost.io)

**Comment by pedrosousa13** [comment]
encountering the same in github actions. Locally works fine. We have the latest storybook version (8.3.3)

**Comment by shilman** [comment]
@VizTheWiz  indeed we are putting a lot of work into the new Vitest stuff, but we will continue to maintain the test runner for the foreseeable future since it's used by a lot of teams, does not require Vite, etc. I'll try to get the team to look into this soon.

**Comment by yannbf** [comment]
Hey everyone! I'd really love to fix this issue, but without a clear reproduction it's tough.
I'd really appreciate to get as much context as possible so I can get to the bottom of this! I have never experienced this issue myself unfortunately.

**Comment by Cuuki** [comment]
Hey @yannbf! Thanks for taking a look here!

I cannot speak for OG, but my team is having flaky tests with the exact same error code. We have not further investigated on our end because of time limitations and since one rerun always seems to fix this for a couple of runs but I had my eyes on this thread in the meantime.

I can unfortunately not give you a reliable reproduction, as this error only happens occasionally for us, but I might be able to help you pinpoint it by providing details of our setup (most of this has been mentioned before):

1. This specific issue **only happens** when testing on `webkit` for us, never with `chromium` or `firefox`.
2. Checking our CI history, this happens about every 4th to 6th run (not very helpful but still 😅).
3. The issue only happens with the `test-runner` and not in the Storybook UI.
4. The error itself always originates in the `preVisit` hook of the `test-runner` config (see image below), where we set up viewports with the `storyContext` and `injectAxe` (see code snippet).
5. The command we use for the CI looks as follows `test-storybook -c src --url http://127.0.0.1:6006 --browsers webkit --junit --ci --maxWorkers=1`.
6. We are currently running Storybook `8.3.5` in a monorepo setup.

I hope this is helpful, let me know if there is anything else I can provide!

![Image](https://github.com/user-attachments/assets/023522e0-b529-4eac-afdf-b95851fbdf4e)

```ts
async preVisit(page, context) {
    await waitForPageReady(page);

    const storyContext = await getStoryContext(page, context);

    // Accesses the story's parameters and retrieves the viewport used to render it
    // https://storybook.js.org/docs/writing-tests/test-runner#accessing-story-information-with-the-test-runner
    const storyViewport =
        storyContext.parameters?.viewport?.defaultViewport;

    const viewportName: ViewportBreakpointToken =
        storyViewport in VIEWPORTS ? storyViewport : DEFAULT_VIEWPORT;

    const { width, height } = VIEWPORTS[viewportName].styles;

    // Configures the Playwright page to use the viewport size
    await page.setViewportSize({
        width: parseFloat(width.replace('px', '')),
        height: parseFloat(height.replace('px', '')),
    });

    await injectAxe(page);
},
```

**Comment by andrejilderda** [comment]
I’ve identified a reliable way to reproduce this issue in my codebase (unfortunately, it’s not open source*).


I have a `test-runner.ts` that is similar to the one in the docs:

```typescript
import {
  getStoryContext,
  type TestRunnerConfig,
  waitForPageReady,
} from "@storybook/test-runner";

import { viewports } from "./viewports";

const DEFAULT_VIEWPORT_SIZE = { width: 1280, height: 720 };

const config: TestRunnerConfig = {
  async preVisit(page, story) {
    await waitForPageReady(page);

    const context = await getStoryContext(page, story);
    const viewportName = context.parameters?.viewport?.defaultViewport;
    const viewportParameter = viewports[viewportName];

    if (viewportParameter?.styles) {
      const viewportSize = Object.entries(viewportParameter.styles).reduce(
        (acc, [screen, size]) => ({
          ...acc,
          // make sure the viewport config in Storybook only uses numbers, not percentages
          [screen]: parseInt(size),
        }),
        {}
      ) as { width: number; height: number };

      page.setViewportSize(viewportSize);
    } else {
      page.setViewportSize(DEFAULT_VIEWPORT_SIZE);
    }
  },
};
export default config;
```

**To reproduce:**
- delete the Storybook cache at `node_modules/.cache/storybook`
- run storybook: `pnpm run storybook`
- run the test runner: `pnpm run test-storybook`
- in my codebase the first few tests fail with `page.evaluate: TypeError: globalThis.__getContext is not a function`

**Two things to note:**
- I'm using `await waitForPageReady(page);` as suggested earlier in this thread to reduce test flakiness.
  - Without this, I’d encounter:
`page.evaluate: SB_PREVIEW_API_0011 (StoryStoreAccessedBeforeInitializationError): Cannot access the Story Store until the index is ready.`
  - However, with it, I now see the error: `page.evaluate: TypeError: globalThis.__getContext is not a function.
- without deleting the cache the tests only fail every once in a while (I assume when dependencies have changed/cache is invalidated)

Perhaps this will help someone in this thread with a reproduction. If not, I'd be happy to share insights or discuss this over a call if that would be useful @yannbf.

**Comment by victorcarvalhosp** [comment]
Do you have any update on this? I'm having the same issue here, but even worse is that if I add `await waitForPageReady(page)` all my tests fail with a timeout:

    `thrown: "Exceeded timeout of 15000 ms for a test. Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout." `

Increasing the timeout doesn't help.

**Comment by sergei-maertens** [comment]
> Interestingly enough, this doesn't seem to happen with a production build since our CI is passing: https://github.com/open-formulieren/open-forms-sdk/actions/runs/8340149970/job/22823603724?pr=663

Switching to the vite builder now makes it fail on CI too :(

**Comment by Frogman135** [comment]
I had the same issue in a project at work.

It happened very randomly, but at least every other time I ran the test.

Adding await waitForPageReady(page); only made it worse and made every test fail.

But extending the timeout by adding _--testTimeout=60000_ to all _npm run test-storybook_ commands fixed the issue for me:

`"test-storybook": "test-storybook --testTimeout=60000",`

I hope this helps anyone.

**Comment by svenvandescheur** [comment]
Currently this hacky approach seems te reduce the impact for me:

```ts
async function waitForStoryContext(
  page: Page,
  story: StoryFn,
  attempt = 1,
  maxAttempts = 20,
) {
  try {
    return await getStoryContext(page, story);
  } catch (e) {
    if (attempt > maxAttempts) {
      throw e;
    }
    // ¯\_(ツ)_/¯ - If this is not the first attempt: add a random timeout.
    await new Promise(resolve => setTimeout(resolve, 600));
    return waitForStoryContext(page, story, attempt + 1);
  }
}

async preVisit(page: Page, story: StoryFn) {
    const context = await waitForStoryContext(page, story);
   // ...
};
```

The idea is to try again but to delay if the first attempt did not work. A. bit hacky but seems to pass for now.

**Comment by akibarika** [comment]
> I’ve identified a reliable way to reproduce this issue in my codebase (unfortunately, it’s not open source*).
> 
> I have a `test-runner.ts` that is similar to the one in the docs:
> 
> import {
>   getStoryContext,
>   type TestRunnerConfig,
>   waitForPageReady,
> } from "@storybook/test-runner";
> 
> import { viewports } from "./viewports";
> 
> const DEFAULT_VIEWPORT_SIZE = { width: 1280, height: 720 };
> 
> const config: TestRunnerConfig = {
>   async preVisit(page, story) {
>     await waitForPageReady(page);
> 
>     const context = await getStoryContext(page, story);
>     const viewportName = context.parameters?.viewport?.defaultViewport;
>     const viewportParameter = viewports[viewportName];
> 
>     if (viewportParameter?.styles) {
>       const viewportSize = Object.entries(viewportParameter.styles).reduce(
>         (acc, [screen, size]) => ({
>           ...acc,
>           // make sure the viewport config in Storybook only uses numbers, not percentages
>           [screen]: parseInt(size),
>         }),
>         {}
>       ) as { width: number; height: number };
> 
>       page.setViewportSize(viewportSize);
>     } else {
>       page.setViewportSize(DEFAULT_VIEWPORT_SIZE);
>     }
>   },
> };
> export default config;
> **To reproduce:**
> 
> * delete the Storybook cache at `node_modules/.cache/storybook`
> * run storybook: `pnpm run storybook`
> * run the test runner: `pnpm run test-storybook`
> * in my codebase the first few tests fail with `page.evaluate: TypeError: globalThis.__getContext is not a function`
> 
> **Three things to note:**
> 
> * It appears to be project-specific. I attempted to create a minimal Vite + Storybook reproduction, but the issue doesn't occur there.
> * I'm using `await waitForPageReady(page);` as suggested earlier in this thread to reduce test flakiness.
>   
>   * Without this, I’d encounter:
>     `page.evaluate: SB_PREVIEW_API_0011 (StoryStoreAccessedBeforeInitializationError): Cannot access the Story Store until the index is ready.`
>   * However, with it, I now see the error: `page.evaluate: TypeError: globalThis.__getContext is not a function.
> * without deleting the cache the tests only fail every once in a while (I assume when dependencies have changed/cache is invalidated)
> 
> Perhaps this will help someone in this thread with a reproduction. *If not, I'd be happy to share insights or discuss this over a call if that would be useful [@yannbf](https://github.com/yannbf).

Hi, any updates on this? I am also encountering this error  `page.evaluate: TypeError: globalThis.__getContext is not a function.`

**Comment by plaa** [comment]
I'm facing the same issue in a work project.  Everything was working fine until I added browser resizing to my `preVisit` which requires calling `getStoryContext`.  For a while it worked, then it became flaky, now it's failing 100% of runs even though I haven't changed the code at all.  We're only running using Chromium locally (contrary to @Cuuki's experience of only occurring on Webkit).

Adding `--maxWorkers=1` fixes the issue, but makes the tests much slower, so not a viable long-term option.  Fortunately @svenvandescheur's [suggestion works](https://github.com/storybookjs/test-runner/issues/442#issuecomment-2697318195) and makes the test runs reliable.  I tested and a 50 ms delay is sufficient that most of the time only a single retry is needed.  I'm using 50 ms and 100 retries for added safety.

All the symptoms indicate this is a concurrency or race condition issue:
- Flaky, it varies which tests and how many fail
- External circumstances affect the outcome, e.g. what computer is used, what browser, what other software is running (initially the tests passed for me, then were flaky, now fail 100% even without any changed, in between I only did `git clean -fdx && npm i`)
- Removing concurrency fixes the issue
- Cannot be reproduced in a minimal example, i.e. requires a certain amount of tests/code to become flaky
- Retrying after a delay helps

I hope this helps tracking down the issue.  In the meantime I recommend [svenvandescheur's suggestion](https://github.com/storybookjs/test-runner/issues/442#issuecomment-2697318195) for everyone facing the issue.

**Comment by plaa** [comment]
And as soon as I posted that ☝ (after I had successfully ran the tests a dozen times), I got a _different_ type of failure which the retry mechanism didn't fix.  Therefore there may be _two_ separate / related issues going on.

My original stack trace:
```
 FAIL  frontend/src/components/CardWithHeader/CardWithHeader.stories.tsx
  ● components/CardWithHeader › Default › smoke-test

    page.evaluate: SB_PREVIEW_API_0011 (StoryStoreAccessedBeforeInitializationError): Cannot access the Story Store until the index is ready.

    It is not recommended to use methods directly on the Story Store anyway, in Storybook 9 we will
    remove access to the store entirely

      at Object.get (frontend/http:/127.0.0.1:6006/node_modules/.cache/storybook/1e8d972d900bca133086bd0f2a507dc200194c3a4e84ff3ab0634962711df360/sb-vite/deps/storybook_internal_preview_runtime.js?v=dcf72e64:8571:17)
      at __getContext (frontend/<anonymous>:219:54)
      at eval (eval at evaluate (:234:30)frontend/, <anonymous>:1:29)
      at UtilityScript.evaluate (frontend/<anonymous>:236:17)
      at UtilityScript.<anonymous> (frontend/<anonymous>:1:44)
      at getStoryContext (frontend/node_modules/@storybook/test-runner/dist/index.js:10160:15)
      at preVisit (frontend/.storybook/test-runner.ts:35:38)
      at frontend/src/components/CardWithHeader/CardWithHeader.stories.tsx:203:64
      at step (frontend/src/components/CardWithHeader/CardWithHeader.stories.tsx:161:23)
      at Object.next (frontend/src/components/CardWithHeader/CardWithHeader.stories.tsx:102:20)
      at asyncGeneratorStep (frontend/src/components/CardWithHeader/CardWithHeader.stories.tsx:4:28)
      at _next (frontend/src/components/CardWithHeader/CardWithHeader.stories.tsx:22:17)
      at frontend/src/components/CardWithHeader/CardWithHeader.stories.tsx:27:13
      at frontend/src/components/CardWithHeader/CardWithHeader.stories.tsx:19:16
      at testFn (frontend/src/components/CardWithHeader/CardWithHeader.stories.tsx:302:49)
      at Object.<anonymous> (frontend/src/components/CardWithHeader/CardWithHeader.stories.tsx:315:33)
      at step (frontend/src/components/CardWithHeader/CardWithHeader.stories.tsx:161:23)
      at Object.next (frontend/src/components/CardWithHeader/CardWithHeader.stories.tsx:102:20)
      at asyncGeneratorStep (frontend/src/components/CardWithHeader/CardWithHeader.stories.tsx:4:28)
      at _next (frontend/src/components/CardWithHeader/CardWithHeader.stories.tsx:22:17)
      at frontend/src/components/CardWithHeader/CardWithHeader.stories.tsx:27:13
      at Object.<anonymous> (frontend/src/components/CardWithHeader/CardWithHeader.stories.tsx:19:16)
```

The error I now got (with the `waitForStoryContext` workaround), with a 5s delay for each test (i.e. the 100 retries being exhausted):
```
 FAIL   browser: chromium  src/components/CardWithHeader/CardWithHeader.stories.tsx (7.941 s)
  ● components/CardWithHeader › Default › smoke-test

    page.evaluate: TypeError: globalThis.__getContext is not a function

      at eval (eval at evaluate (:234:30)frontend/, <anonymous>:1:29)
      at UtilityScript.evaluate (frontend/<anonymous>:236:17)
      at UtilityScript.<anonymous> (frontend/<anonymous>:1:44)
      at getStoryContext (frontend/node_modules/@storybook/test-runner/dist/index.js:10160:15)
      at waitForStoryContext (frontend/.storybook/test-runner.ts:19:33)
      at waitForStoryContext (frontend/.storybook/test-runner.ts:25:12)
      at preVisit (frontend/.storybook/test-runner.ts:35:17)
```

A couple of tests had time to pass, and after that every test stalled for 5 seconds and printed that error message.

Fortunately this other flakiness seems rare, I ran the tests another dozen times without getting it again, so hopefully we can live with it.  Will have to see does it trigger in CI.  😕

**Comment by maertz** [comment]
SB_PREVIEW_API_0011 brought me here, somehow all previous mentioned ways did not work for me. So I gave it a shot to use postVisit in combintion with the next animation frame to ensure my story is properly rendered before I take my screenshot afterwards.

Works pretty well in my case.

`
// Force wait for next animation frame (ensures rendering is complete)
    await page.evaluate(() => {
      return new Promise<void>((resolve) => {
        requestAnimationFrame(() => {
          requestAnimationFrame(() => {
            resolve();
          });
        });
      });
    });`

**Comment by joshua-gomes-meandem** [comment]
This issue doesn't seem to be resolved yet in storybook as of Storybook 9.1.7.

The solution that worked for me was the one posted by @svenvandescheur:
https://github.com/storybookjs/test-runner/issues/442#issuecomment-2697318195

**Comment by magicknot** [comment]
I'm also having this issue, on Storybook 10 when I try to customize the viewport size to use what is defined in a Story. My end goal was to replace `storycap` with [storycap-testrun](https://storybook.js.org/addons/storycap-testrun).
