### ISSUE TITLE
[Bug]: Executable doesn't exist

### ISSUE THREAD

**Issue by ianzone** [storybookjs/test-runner#531]
### Describe the bug

```bash
> react-storybook-template@0.0.0 test /home/ian/templates/react-storybook
> test-storybook

(node:211630) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Test Suites: 0 of 4 total
Tests:       0 total
Snapshots:   0 total
Time:        0.24 s
Ran all test suites.
Error: Executable doesn't exist at /home/ian/.cache/ms-playwright/chromium_headless_shell-1148/chrome-linux/headless_shell
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     pnpm exec playwright install                                        ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝ Failed to launch browser.
    at executablePathOrDie (/home/ian/templates/react-storybook/node_modules/.pnpm/playwright-core@1.49.1/node_modules/playwright-core/lib/server/registry/index.js:394:15)
    at Object.executablePathOrDie (/home/ian/templates/react-storybook/node_modules/.pnpm/playwright-core@1.49.1/node_modules/playwright-core/lib/server/registry/index.js:424:43)
    at Chromium._launchProcess (/home/ian/templates/react-storybook/node_modules/.pnpm/playwright-core@1.49.1/node_modules/playwright-core/lib/server/browserType.js:203:39)
    at async Chromium._innerLaunch (/home/ian/templates/react-storybook/node_modules/.pnpm/playwright-core@1.49.1/node_modules/playwright-core/lib/server/browserType.js:139:9)
    at async Chromium._innerLaunchWithRetries (/home/ian/templates/react-storybook/node_modules/.pnpm/playwright-core@1.49.1/node_modules/playwright-core/lib/server/browserType.js:120:14)
    at async ProgressController.run (/home/ian/templates/react-storybook/node_modules/.pnpm/playwright-core@1.49.1/node_modules/playwright-core/lib/server/progress.js:79:22)
    at async Chromium.launch (/home/ian/templates/react-storybook/node_modules/.pnpm/playwright-core@1.49.1/node_modules/playwright-core/lib/server/browserType.js:79:21)
    at async BrowserServerLauncherImpl.launchServer (/home/ian/templates/react-storybook/node_modules/.pnpm/playwright-core@1.49.1/node_modules/playwright-core/lib/browserServerImpl.js:48:21)
    at async BrowserType.launchServer (/home/ian/templates/react-storybook/node_modules/.pnpm/playwright-core@1.49.1/node_modules/playwright-core/lib/client/browserType.js:82:12)
    at async PlaywrightRunner.launchServer (/home/ian/templates/react-storybook/node_modules/.pnpm/jest-playwright-preset@4.0.0_jest-circus@29.7.0_jest-environment-node@29.7.0_jest-runner@29.7_3w53sh4gg6ep6p6kymmqcxba5m/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:69:44)
 ELIFECYCLE  Test failed. See above for more details.
```

### To Reproduce

1. clone https://github.com/ianzone/react-storybook
2. pnpm i
3. pnpm run dev
4. pnpm run test

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13800H
    Shell: 5.9 - /home/linuxbrew/.linuxbrew/bin/zsh
  Binaries:
    Node: 22.12.0 - /home/linuxbrew/.linuxbrew/opt/node@22/bin/node
    npm: 10.9.0 - /home/linuxbrew/.linuxbrew/opt/node@22/bin/npm
    pnpm: 9.15.2 - /home/linuxbrew/.linuxbrew/bin/pnpm <----- active
  npmPackages:
    @storybook/addon-essentials: ^8.4.7 => 8.4.7
    @storybook/addon-interactions: ^8.4.7 => 8.4.7
    @storybook/addon-links: ^8.4.7 => 8.4.7
    @storybook/blocks: ^8.4.7 => 8.4.7
    @storybook/react: ^8.4.7 => 8.4.7
    @storybook/react-vite: ^8.4.7 => 8.4.7
    @storybook/test: ^8.4.7 => 8.4.7
    @storybook/test-runner: ^0.21.0 => 0.21.0
    storybook: ^8.4.7 => 8.4.7
```

**Comment by ianzone** [comment]
it turned out that the headless browsers were not installed, run `pnpx playwright install --with-deps` to fix this issue.
