### ISSUE TITLE
[Bug] Storybook fail on start after adding '@storybook/addon-interactions' to .storybook/main.js 

### ISSUE THREAD

**Issue by ArmandDu** [storybookjs/test-runner#75]
### Describe the bug

After installing `@storybook/test-runner` and following the [Getting Started](https://storybook.js.org/addons/@storybook/test-runner#getting-started) documentation, starting storybook fails to start and throws the following error:

```
ModuleNotFoundError: Module not found: Error: Can't resolve './.storybook/@storybook' in </home/....>
```

### Steps to reproduce the behavior

1. Install storybook/react 6.4.19 with addon-essentuals, addon-actions, addon-interaction, add-links
2. Install @storybook/jest 0.0.9 and @storybook/testing-library 0.0.9
3. install `@storybook/test-runner` 0.0.4
4. Follow the getting started and add this to the `./storybook/main.js`:  
```module.exports = {
  stories: ['@storybook/addon-interactions'],
  features: {
    interactionsDebugger: true,
  },
};
```
5. run storybook `yarn storybook` (in my case `npm run storybook`)
6. Storybook fail to start with error:

```
ModuleNotFoundError: Module not found: Error: Can't resolve './.storybook/@storybook' in </home/....>
```
### Expected behavior

Storybook should be able to start without error.

### Screenshots and/or logs

`npm run storybook` logs:
```
ModuleNotFoundError: Module not found: Error: Can't resolve './.storybook/@storybook' in '~/web-app'
    at ~/web-app/node_modules/webpack/lib/Compilation.js:2014:28
    at ~/web-app/node_modules/webpack/lib/ContextModuleFactory.js:210:15
    at ~/web-app/node_modules/neo-async/async.js:2830:7
    at ~/web-app/node_modules/neo-async/async.js:6877:13
    at ~/web-app/node_modules/webpack/lib/ContextModuleFactory.js:180:26
    at finishWithoutResolve (~/web-app/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:307:11)
    at ~/web-app/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:381:15
    at ~/web-app/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:430:5
    at eval (eval at create (~/web-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at ~/web-app/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:430:5
    at eval (eval at create (~/web-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at ~/web-app/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at ~/web-app/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:430:5
    at eval (eval at create (~/web-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at ~/web-app/node_modules/webpack/node_modules/enhanced-resolve/lib/forEachBail.js:16:12
    at ~/web-app/node_modules/webpack/node_modules/enhanced-resolve/lib/AliasPlugin.js:103:14
resolve './.storybook/@storybook' in '~/web-app'
  using description file: ~/web-app/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: ~/web-app/package.json (relative path: ./.storybook/@storybook)
      ~/web-app/.storybook/@storybook doesn't exist
```

Dev Dependencies:
```
"@babel/core": "^7.17.5",
"@storybook/addon-actions": "^6.4.19",
"@storybook/addon-essentials": "^6.4.19",
"@storybook/addon-interactions": "^6.4.19",
"@storybook/addon-links": "^6.4.19",
"@storybook/builder-webpack5": "^6.4.19",
"@storybook/jest": "^0.0.9",
"@storybook/manager-webpack5": "^6.4.19",
"@storybook/react": "^6.4.19",
"@storybook/test-runner": "^0.0.4",
"@storybook/testing-library": "^0.0.9",
"webpack": "^5.69.1",
"webpack-merge": "^5.8.0"
```

### Environment

 - OS: Arch/Manjaro
 - Node.js version: v16.8.0
 - NPM version: 7.21.0
 - Browser (if applicable): Firefox
 - Browser version (if applicable): 98 
 - Device (if applicable):

**Comment by ArmandDu** [comment]
After waking up a little, I noticed that adding this line to .storybook/main.js was a bit weird:
```stories: ['@storybook/addon-interactions'],
```

After waking up a little more, I realized that it's probably a typo as it's not even the same plugin name.

Removing this line and properly running `npm run storybook` then `npm run test-storybook` now works.

My initial half awake guess seems to be right, there's an issue in the Doc page.
