### ISSUE TITLE
TypeError: Jest: a transform must export a `process` function

### ISSUE THREAD

**Issue by jeremyzilar** [storybookjs/test-runner#77]
👋 I am trying to add `test-runner` to an existing project that already has Storybook and Jest running, when following the **Getting started** instructions, I end up with the following error for each of my existing stories:

```
 FAIL   browser: chromium  spec/storybook/pages/request/index.stories.tsx
  ● Test suite failed to run

    TypeError: Jest: a transform must export a `process` function.

      at ScriptTransformer._getTransformer (node_modules/@jest/transform/build/ScriptTransformer.js:360:13)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:427:28)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:569:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:607:25)
      at interopRequireDefault (node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js:64:16)
```

## Steps to reproduce

1. run `yarn storybook` in terminal, wait for it to finish
1. run `yarn test-storybook` in another terminal

## Current packages
- My major versions of `ts-jest` and `jest` match.
- I am using Webpack 4

Any thoughts on this?

**Comment by jeremyzilar** [comment]
FYI, this seemed to solve it https://github.com/kulshekhar/ts-jest/issues/2612#issuecomment-851489317
Updating `react-scripts` fixed it. It was importing an older version dependency.
